version: '3.8'

services:

  mariadb:
    restart: always
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - "24045:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./log/mysql:/var/log/mysql
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=1234a
      - MYSQL_DATABASE=local
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=1234a
      - TZ=Asia/Seoul

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "37421:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "10520:6379"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "85:85"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet
      
volumes:
  mariadb_data:
  mongodb_data:
  
networks:
  mysqlnetwork:
    driver: bridge
  webnet: